import { useState, createContext, useContext } from 'react';
import { Language } from '../types';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations = {
  en: {
    'app.title': 'CondoShield',
    'app.tagline': 'Protect Your Property Rights',
    'nav.dashboard': 'Dashboard',
    'nav.analyzer': 'Analyzer',
    'nav.legal': 'Legal Assistant',
    'nav.community': 'Community',
    'nav.costsavings': 'Cost Savings',
    'nav.generator': 'Letter Generator',
    'dashboard.title': 'Your Property Protection Dashboard',
    'dashboard.subtitle': 'Track assessments, disputes, and protect your rights',
    'dashboard.totalAssessments': 'Total Assessments',
    'dashboard.activeDisputes': 'Active Disputes',
    'dashboard.savedAmount': 'Potential Saved Amount',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.viewAll': 'View All',
    'dashboard.noActivity': 'No recent activity',
    'analyzer.title': 'Assessment Analyzer',
    'analyzer.subtitle': 'Upload and analyze your property assessments',
    'analyzer.upload': 'Upload Assessment',
    'analyzer.manual': 'Manual Entry',
    'analyzer.dragDrop': 'Drag and drop your PDF or image here',
    'analyzer.fileTypes': 'Supports PDF, JPG, PNG files',
    'analyzer.processing': 'Processing assessment...',
    'analyzer.results': 'Analysis Results',
    'analyzer.breakdown': 'Cost Breakdown',
    'analyzer.questionable': 'Potentially Questionable',
    'analyzer.normal': 'Normal',
    'legal.title': 'Legal Assistant',
    'legal.subtitle': 'Get personalized legal guidance for your region',
    'legal.askQuestion': 'Ask a Legal Question',
    'legal.placeholder': 'e.g., Can I refuse to pay a special assessment with no breakdown?',
    'legal.submit': 'Get Legal Guidance',
    'legal.processing': 'Analyzing your question...',
    'legal.commonQuestions': 'Common Questions',
    'community.title': 'Owner Community',
    'community.subtitle': 'Connect with verified property owners worldwide',
    'community.search': 'Search by location, issue, etc.',
    'community.filter': 'Filter by Category',
    'community.all': 'All Posts',
    'community.warnings': 'Warnings',
    'community.success': 'Success Stories',
    'community.questions': 'Questions',
    'community.advice': 'Advice',
    'community.newPost': 'New Post',
    'community.upvotes': 'upvotes',
    'community.replies': 'replies',
    'community.sort.mostUpvotes': 'Most Upvotes',
    'community.sort.leastUpvotes': 'Least Upvotes',
    'community.sort.mostReplies': 'Most Replies',
    'community.sort.leastReplies': 'Least Replies',
    'community.noResults': 'No posts found matching your criteria.',
    'community.byAuthor': 'by',
    'generator.title': 'Dispute Letter Generator',
    'generator.subtitle': 'Generate professional dispute letters',
    'generator.selectAssessment': 'Select Assessment to Dispute',
    'generator.recipientName': 'Recipient Name',
    'generator.recipientTitle': 'Recipient Title',
    'generator.yourConcerns': 'Your Concerns',
    'generator.concernsPlaceholder': 'Describe your specific concerns about this assessment...',
    'generator.generateLetter': 'Generate Letter',
    'generator.downloadPdf': 'Download PDF',
    'generator.copyText': 'Copy Text',
    'settings.language': 'Language',
    'settings.region': 'Your Region',
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.success': 'Success!',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.close': 'Close',
    'savings.title': 'Cost Savings Suggestions',
    'savings.subtitle': 'Use AI to identify areas where you might reduce unnecessary charges.',
    'savings.selectAssessment': 'Select an assessment',
    'savings.generate': 'Generate Suggestions',
    'savings.generating': 'Analyzing...',
    'savings.copy': 'Copy Text',
    'savings.resultHeader': 'Suggested Cost Reductions',
    "regions.northAmerica": "North America",
    "regions.europe": "Europe",
    "regions.asia": "Asia",
    "regions.other": "Other",
    "countries.canada": "Canada",
    "countries.usa": "USA",
    "countries.mexico": "Mexico",
    "countries.uk": "United Kingdom",
    "countries.germany": "Germany",
    "countries.france": "France",
    "countries.india": "India",
    "countries.china": "China",
    "countries.japan": "Japan",
    "countries.other": "Other",
    "dashboard.totalAmount": "Total Amount",
  "dashboard.upcomingDeadlines": "Upcoming Deadlines",
  "dashboard.noUpcomingDeadlines": "No upcoming deadlines",
  "dashboard.addDeadline": "Add Deadline",
  "dashboard.selectDate": "Select date and time",
  "dashboard.addReminder": "Add Reminder",

  "dueDate": "Due date",
  "close": "Close",
  "yourAssessments": "Your Assessments",
  "lastUpdated": "Last updated:",
  "potentialSaved": "Potential Saved:",
  "generatedOn": "Generated on:",

  "allActivity": "All Activity",
  "loadingActivity": "Loading activity...",
  "noActivityFound": "No activity found.",
  "loadMore": "Load more",
  "minAgo": "min ago",
  "hrsAgo": "hrs ago",
  "daysAgo": "days ago",

  "loadingReminders": "Loading reminders...",
  "noRemindersFound": "No reminders found.",

  "legal.commonQuestion1": "Can I refuse to pay a special assessment without detailed breakdown?",
  "legal.commonQuestion2": "What are my rights when charged excessive late fees?",
  "legal.commonQuestion3": "How long does my HOA have to provide financial documentation?",
  "legal.commonQuestion4": "Can emergency assessments be charged without owner approval?",

  "general": "General",
  "assessmentRights": "Assessment Rights",
  "feeDisputes": "Fee Disputes",
  "documentationRights": "Documentation Rights",
  "emergencyFees": "Emergency Fees",

  "askedLegalQuestion": "Asked a legal question for region:",
  "yourRegion": "Your Region:",
  "legalGuidance": "Legal guidance will be tailored to your jurisdiction.",
  "changeRegion": "Change region",
  "legalGuid": "Legal Guidance",

  "selectRegion": "Select Your Region",
  "continent": "Continent",
  "country": "Country",
  "provinceSlashState": "State/Province (optional)",
  "exampleProvinceOrStateText": "e.g. Ontario, California",
  "saveRegion": "Save Region",
  'newPostModal.title': 'Create New Post',
  'newPostModal.placeholder.title': 'Title',
  'newPostModal.placeholder.content': 'Content',
  'newPostModal.placeholder.region': 'Region (e.g., Miami, FL)',
  'newPostModal.category.warning': 'Warning',
  'newPostModal.category.success': 'Success',
  'newPostModal.category.question': 'Question',
  'newPostModal.category.advice': 'Advice',
  'newPostModal.anonymous.postingAnonymous': 'Posting as Anonymous',
  'newPostModal.anonymous.postingNamed': 'Posting with Name',
  'newPostModal.button.cancel': 'Cancel',
  'newPostModal.button.post': 'Post',
  'newPostModal.error.notLoggedIn': 'You must be logged in to post.',
  'postDetail.back': 'Back',
  'postDetail.by': 'by',
  'postDetail.upvotes': 'Upvotes',
  'postDetail.reply.title': 'Reply',
  'postDetail.reply.placeholder': 'Write a reply...',
  'postDetail.reply.anonymousOn': 'Replying Anonymously',
  'postDetail.reply.anonymousOff': 'Reply Anonymously',
  'postDetail.reply.submit': 'Submit',
  'postDetail.replies.title': 'Replies',
  'postDetail.replies.empty': 'No replies yet. Be the first!',
  'postDetail.alert.notLoggedIn': 'You must be logged in to reply.',
  "savings.selectPlaceholder": "Select an assessment...",
  "savings.noOpportunities": "After reviewing your assessment, no immediate cost-saving opportunities were found.",
  "savings.estSavings": "Estimated Savings",
  "savings.emailSubject": "Subject: Recommendations for Cost Savings",
  "savings.emailIntro": "Based on your condo assessment, here are some actionable cost-saving suggestions totaling approximately ${{total}}:",
  "savings.emailNote": "We recommend reviewing these items and discussing them with your association board or property manager.",
  "savings.emailClosing": "Sincerely",
   "dispute.trigger": "Generate Dispute Letter",
  "dispute.generating": "Generating...",
  "dispute.editableTitle": "Editable Dispute Letter",
  "dispute.savedTitle": "Saved Dispute Letter",
  "dispute.save": "Save Dispute",
  "dispute.saving": "Saving...",
  "dispute.saved": "Saved",
  "dispute.exportPdf": "Export PDF",
  "dispute.exportWord": "Export Word",
  "dispute.sendGmail": "Send via Gmail",
  "dispute.emailSubject": "Condo Dispute Letter",
  "auth.loginTitle": "Log In",
  "auth.signupTitle": "Sign Up",
  "auth.displayName": "Display Name",
  "auth.email": "Email",
  "auth.password": "Password",
  "auth.loginButton": "Login",
  "auth.signupButton": "Sign Up",
  "auth.google": "Continue with Google",
  "auth.noAccount": "Don't have an account?",
  "auth.signupLink": "Sign up",
  "auth.hasAccount": "Already have an account?",
  "auth.loginLink": "Log in",
  "auth.logout": "Logout",
  "auth.anonymous": "Anonymous",
  "legal.loadingSession": "Loading legal session...",
  "auth.signupSuccess": "✅ Signup successful! Please check your email to confirm your account. Make sure to check your junk or spam folder. Once confirmed, you can log in.",
  },
  fr: {
    'app.title': 'CondoShield',
    'app.tagline': 'Protégez Vos Droits Immobiliers',
    'nav.dashboard': 'Tableau de Bord',
    'nav.analyzer': 'Analyseur',
    'nav.legal': 'Assistant Juridique',
    'nav.community': 'Communauté',
    'nav.costsavings': 'Économies de coûts',
    'nav.generator': 'Générateur de Lettres',
    'dashboard.title': 'Votre Tableau de Bord de Protection Immobilière',
    'dashboard.subtitle': 'Suivez les évaluations, les litiges et protégez vos droits',
    'dashboard.totalAssessments': 'Évaluations Totales',
    'dashboard.activeDisputes': 'Litiges Actifs',
    'dashboard.savedAmount': 'Montant potentiellement économisé',
    'dashboard.recentActivity': 'Activité Récente',
    'dashboard.viewAll': 'Voir Tout',
    'dashboard.noActivity': 'Aucune activité récente',
    'analyzer.title': 'Analyseur d\'Évaluation',
    'analyzer.subtitle': 'Téléchargez et analysez vos évaluations immobilières',
    'analyzer.upload': 'Télécharger Évaluation',
    'analyzer.manual': 'Saisie Manuelle',
    'analyzer.dragDrop': 'Glissez et déposez votre PDF ou image ici',
    'analyzer.fileTypes': 'Supporte les fichiers PDF, JPG, PNG',
    'analyzer.processing': 'Traitement de l\'évaluation...',
    'analyzer.results': 'Résultats d\'Analyse',
    'analyzer.breakdown': 'Répartition des Coûts',
    'analyzer.questionable': 'Potentiellement Questionnable',
    'analyzer.normal': 'Normal',
    'legal.title': 'Assistant Juridique',
    'legal.subtitle': 'Obtenez des conseils juridiques personnalisés pour votre région',
    'legal.askQuestion': 'Poser une Question Juridique',
    'legal.placeholder': 'ex: Puis-je refuser de payer une évaluation spéciale sans détail?',
    'legal.submit': 'Obtenir des Conseils Juridiques',
    'legal.processing': 'Analyse de votre question...',
    'legal.commonQuestions': 'Questions Fréquentes',
    'community.title': 'Communauté des Propriétaires',
    'community.subtitle': 'Connectez-vous avec des propriétaires vérifiés du monde entier',
    'community.search': 'Recherche par lieu, par problème, etc.',
    'community.filter': 'Filtrer par Catégorie',
    'community.all': 'Tous les Posts',
    'community.warnings': 'Avertissements',
    'community.success': 'Histoires de Succès',
    'community.questions': 'Questions',
    'community.advice': 'Conseils',
    'community.newPost': 'Nouveau Post',
    'community.upvotes': 'votes positifs',
    'community.replies': 'réponses',
    'community.sort.mostUpvotes': 'Le plus de votes',
    'community.sort.leastUpvotes': 'Le moins de votes',
    'community.sort.mostReplies': 'Le plus de réponses',
    'community.sort.leastReplies': 'Le moins de réponses',
    'community.noResults': 'Aucun post ne correspond à vos critères.',
    'community.byAuthor': 'par',
    'generator.title': 'Générateur de Lettres de Contestation',
    'generator.subtitle': 'Générez des lettres de contestation professionnelles',
    'generator.selectAssessment': 'Sélectionner l\'Évaluation à Contester',
    'generator.recipientName': 'Nom du Destinataire',
    'generator.recipientTitle': 'Titre du Destinataire',
    'generator.yourConcerns': 'Vos Préoccupations',
    'generator.concernsPlaceholder': 'Décrivez vos préoccupations spécifiques concernant cette évaluation...',
    'generator.generateLetter': 'Générer la Lettre',
    'generator.downloadPdf': 'Télécharger PDF',
    'generator.copyText': 'Copier le Texte',
    'settings.language': 'Langue',
    'settings.region': 'Votre Région',
    'common.loading': 'Chargement...',
    'common.error': 'Une erreur s\'est produite',
    'common.success': 'Succès!',
    'common.cancel': 'Annuler',
    'common.save': 'Sauvegarder',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.close': 'Fermer',
    'savings.title': 'Suggestions d\'économies',
    'savings.subtitle': 'Utilisez l\'IA pour identifier les domaines dans lesquels vous pourriez réduire les frais inutiles.',
    'savings.selectAssessment': 'Sélectionner une évaluation',
    'savings.generate': 'Générer des suggestions',
    'savings.generating': 'Analyser...',
    'savings.copy': 'Copier le texte',
    'savings.resultHeader': 'Réductions de coûts suggérées',
    "regions.northAmerica": "Amérique du Nord",
    "regions.europe": "Europe",
    "regions.asia": "Asie",
    "regions.other": "Autre",
    "countries.canada": "Canada",
    "countries.usa": "États-Unis",
    "countries.mexico": "Mexique",
    "countries.uk": "Royaume-Uni",
    "countries.germany": "Allemagne",
    "countries.france": "France",
    "countries.india": "Inde",
    "countries.china": "Chine",
    "countries.japan": "Japon",
    "countries.other": "Autre",
    "dashboard.totalAmount": "Montant total",
    "dashboard.upcomingDeadlines": "Prochaines échéances",
    "dashboard.noUpcomingDeadlines": "Aucune échéance à venir",
    "dashboard.addDeadline": "Ajouter un délai",
    "dashboard.selectDate": "Sélectionner la date et l'heure",
    "dashboard.addReminder": "Ajouter un rappel",

    "dueDate": "Date d'échéance",
    "close": "Fermer",
    "yourAssessments": "Vos évaluations",
    "lastUpdated": "Dernière mise à jour :",
    "potentialSaved": "Économies potentielles :",
    "generatedOn": "Généré le :",

    "allActivity": "Toute l'activité",
    "loadingActivity": "Chargement de l'activité...",
    "noActivityFound": "Aucune activité trouvée.",
    "loadMore": "Charger plus",
    "minAgo": "il y a min",
    "hrsAgo": "il y a h",
    "daysAgo": "il y a jours",

    "loadingReminders": "Chargement des rappels...",
    "noRemindersFound": "Aucun rappel trouvé.",

    "legal.commonQuestion1": "Puis-je refuser de payer une cotisation spéciale sans répartition détaillée ?",
    "legal.commonQuestion2": "Quels sont mes droits en cas de frais de retard excessifs ?",
    "legal.commonQuestion3": "Combien de temps mon HOA dispose-t-il pour fournir la documentation financière ?",
    "legal.commonQuestion4": "Des cotisations d'urgence peuvent-elles être imposées sans l'approbation des propriétaires ?",

    "general": "Général",
    "assessmentRights": "Droits relatifs aux cotisations",
    "feeDisputes": "Litiges de frais",
    "documentationRights": "Droits à la documentation",
    "emergencyFees": "Frais d'urgence",

    "askedLegalQuestion": "Question juridique posée pour la région :",
    "yourRegion": "Votre région :",
    "legalGuidance": "Les conseils juridiques seront adaptés à votre juridiction.",
    "changeRegion": "Changer de région",
    "legalGuid": "Conseils juridiques",

    "selectRegion": "Sélectionnez votre région",
    "continent": "Continent",
    "country": "Pays",
    "provinceSlashState": "État/Province (facultatif)",
    "exampleProvinceOrStateText": "ex. Ontario, Californie",
    "saveRegion": "Enregistrer la région",
    'newPostModal.title': 'Créer un nouveau post',
    'newPostModal.placeholder.title': 'Titre',
    'newPostModal.placeholder.content': 'Contenu',
    'newPostModal.placeholder.region': 'Région (ex. : Miami, FL)',
    'newPostModal.category.warning': 'Avertissement',
    'newPostModal.category.success': 'Succès',
    'newPostModal.category.question': 'Question',
    'newPostModal.category.advice': 'Conseil',
    'newPostModal.anonymous.postingAnonymous': 'Publication anonyme',
    'newPostModal.anonymous.postingNamed': 'Publication avec nom',
    'newPostModal.button.cancel': 'Annuler',
    'newPostModal.button.post': 'Publier',
    'newPostModal.error.notLoggedIn': "Vous devez être connecté pour publier.",
    'postDetail.back': 'Retour',
    'postDetail.by': 'par',
    'postDetail.upvotes': 'Votes positifs',
    'postDetail.reply.title': 'Réponse',
    'postDetail.reply.placeholder': 'Écrire une réponse...',
    'postDetail.reply.anonymousOn': 'Répondre anonymement',
    'postDetail.reply.anonymousOff': 'Répondre anonymement',
    'postDetail.reply.submit': 'Envoyer',
    'postDetail.replies.title': 'Réponses',
    'postDetail.replies.empty': 'Pas encore de réponses. Soyez le premier !',
    'postDetail.alert.notLoggedIn': "Vous devez être connecté pour répondre.",
    "savings.selectPlaceholder": "Sélectionnez une évaluation...",
    "savings.noOpportunities": "Après examen de votre évaluation, aucune opportunité d'économie immédiate n'a été trouvée.",
    "savings.estSavings": "Économies estimées",
    "savings.emailSubject": "Objet : Recommandations pour des économies de coûts",
    "savings.emailIntro": "Selon votre évaluation du condo, voici quelques suggestions d'économies réalisables totalisant environ {{total}} $ :",
    "savings.emailNote": "Nous vous recommandons d'examiner ces points et d'en discuter avec votre conseil d'association ou gestionnaire immobilier.",
    "savings.emailClosing": "Cordialement",
    "dispute.trigger": "Générer une lettre de contestation",
    "dispute.generating": "Génération en cours...",
    "dispute.editableTitle": "Lettre de contestation modifiable",
    "dispute.savedTitle": "Lettre de contestation enregistrée",
    "dispute.save": "Enregistrer la contestation",
    "dispute.saving": "Enregistrement en cours...",
    "dispute.saved": "Enregistré",
    "dispute.exportPdf": "Exporter en PDF",
    "dispute.exportWord": "Exporter en Word",
    "dispute.sendGmail": "Envoyer via Gmail",
    "dispute.emailSubject": "Condo Dispute Letter",
    "auth.loginTitle": "Se connecter",
    "auth.signupTitle": "S'inscrire",
    "auth.displayName": "Nom d'affichage",
    "auth.email": "E-mail",
    "auth.password": "Mot de passe",
    "auth.loginButton": "Connexion",
    "auth.signupButton": "Inscription",
    "auth.google": "Continuer avec Google",
    "auth.noAccount": "Vous n'avez pas de compte ?",
    "auth.signupLink": "Inscrivez-vous",
    "auth.hasAccount": "Vous avez déjà un compte ?",
    "auth.loginLink": "Connectez-vous",
    "auth.logout": "Déconnexion",
    "auth.anonymous": "Anonyme",
    "legal.loadingSession": "Chargement de la session juridique...",
    "auth.signupSuccess": "✅ Inscription réussie ! Veuillez vérifier votre e-mail pour confirmer votre compte. N'oubliez pas de vérifier votre dossier de courriers indésirables ou spam. Une fois confirmé, vous pourrez vous connecter."
  }
};

export const useTranslation = (language: Language) => {
  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return { t };
};